# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SpMeta <- function(mcmc_samples, theta_hat, se, x, model_indicator, neighbors = NULL, metrop_var_rho_trans = NULL, a_sigma2_prior = NULL, b_sigma2_prior = NULL, sigma2_beta_prior = NULL, a_tau2_prior = NULL, b_tau2_prior = NULL, sigma2_init = NULL, beta_init = NULL, phi_init = NULL, tau2_init = NULL, rho_init = NULL) {
    .Call(`_SpMeta_SpMeta`, mcmc_samples, theta_hat, se, x, model_indicator, neighbors, metrop_var_rho_trans, a_sigma2_prior, b_sigma2_prior, sigma2_beta_prior, a_tau2_prior, b_tau2_prior, sigma2_init, beta_init, phi_init, tau2_init, rho_init)
}

beta_1_update <- function(n, p_x, x, sigma2_beta, theta_true, tau2_old, Q) {
    .Call(`_SpMeta_beta_1_update`, n, p_x, x, sigma2_beta, theta_true, tau2_old, Q)
}

beta_update <- function(n, p_x, x, sigma2_beta, theta_true, sigma2, phi_old) {
    .Call(`_SpMeta_beta_update`, n, p_x, x, sigma2_beta, theta_true, sigma2, phi_old)
}

phi_update <- function(n, m, x, theta_true, sigma2, beta, tau2_old, Q) {
    .Call(`_SpMeta_phi_update`, n, m, x, theta_true, sigma2, beta, tau2_old, Q)
}

rho_1_update <- function(n, m, x, W, theta_true, beta, tau2, rho_old, Q, Q_log_deter, metrop_sd_rho_trans, acctot_rho_trans) {
    .Call(`_SpMeta_rho_1_update`, n, m, x, W, theta_true, beta, tau2, rho_old, Q, Q_log_deter, metrop_sd_rho_trans, acctot_rho_trans)
}

rho_update <- function(n, m, W, phi, tau2, rho_old, Q, Q_log_deter, metrop_sd_rho_trans, acctot_rho_trans) {
    .Call(`_SpMeta_rho_update`, n, m, W, phi, tau2, rho_old, Q, Q_log_deter, metrop_sd_rho_trans, acctot_rho_trans)
}

sigma2_update <- function(n, m, x, a_sigma2, b_sigma2, theta_true, beta_old, phi_old) {
    .Call(`_SpMeta_sigma2_update`, n, m, x, a_sigma2, b_sigma2, theta_true, beta_old, phi_old)
}

tau2_1_update <- function(n, m, x, a_tau2, b_tau2, theta_true, beta, Q) {
    .Call(`_SpMeta_tau2_1_update`, n, m, x, a_tau2, b_tau2, theta_true, beta, Q)
}

tau2_update <- function(n, m, a_tau2, b_tau2, phi, Q) {
    .Call(`_SpMeta_tau2_update`, n, m, a_tau2, b_tau2, phi, Q)
}

theta_true_1_update <- function(theta_hat, Omega_inv, n, m, x, beta_old, tau2_old, Q) {
    .Call(`_SpMeta_theta_true_1_update`, theta_hat, Omega_inv, n, m, x, beta_old, tau2_old, Q)
}

theta_true_update <- function(theta_hat, Omega_inv, n, m, x, sigma2_old, beta_old, phi_old) {
    .Call(`_SpMeta_theta_true_update`, theta_hat, Omega_inv, n, m, x, sigma2_old, beta_old, phi_old)
}

